services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  WechatPayBundle\Command\:
    resource: '../../Command/'
  WechatPayBundle\Controller\:
    resource: '../../Controller/'
  WechatPayBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  WechatPayBundle\MessageHandler\:
    resource: '../../MessageHandler/'
  WechatPayBundle\Procedure\:
    resource: '../../Procedure/'
  WechatPayBundle\Repository\:
    resource: '../../Repository/'
  WechatPayBundle\Service\:
    resource: '../../Service/'
